# Generated by Django 4.0 on 2022-03-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_performance_monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
